# -*- coding: utf-8 -*-
"""Data analysis on Black Friday sales .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXDWRw4R06nyZg8nta5b3DkAGZrBLux_
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

df = pd.read_csv("BlackFriday.csv")
df.shape

df.head()

df.info()

df.describe()

df.isnull().sum()

# remove null columns
del df["Product_Category_2"]
del df["Product_Category_3"]

df

a = df["User_ID"].nunique()
print("User_ID = ",a)

b = df["Product_ID"].nunique()
print("Product_ID = ",b)

c = df["Gender"].unique()
print("Gender = ",c)

d = df["Age"].unique()
print("Age = ",d)

e = df["Occupation"].unique()
print("Occupation = ",e)

f = df["City_Category"].unique()
print("City_Category = ",f)

g = df["Stay_In_Current_City_Years"].unique()
print("Stay_In_Current_City_Years = ",g)

h = df["Marital_Status"].unique()
print("Marital_Status = ",h)

i = df["Product_Category_1"].unique()
print("Product_Category_1 = ",i)

j = df["Purchase"].nunique()
print("Purchase = ",j)

for columns in df.columns:
    print(df[columns].nunique(), "\t:", columns)

"""# **Analysing Gender wise**"""

# total Number of male and female from the total user in percentile
# 405380 - M (print(df['Gender'].tolist().count('M')) or len(df[df["Gender"] == "M"]) or **df.groupby("Gender").size()**)
# 132197 - F (print(df['Gender'].tolist().count('F')) or len(df[df["Gender"] == "F"]))
# ----------
# 537577 - total
data = pd.DataFrame({"Ratio" : [len(df[df["Gender"] == "M"]),len(df[df["Gender"] == "F"])]}, index=["Male", "Female"])
data.plot.pie(y="Ratio",autopct = "%.1f%%", title = "Gender Ratio", figsize = (4,4))

df.groupby("Gender").size().plot(kind = "pie",autopct = "%.1f%%",title = "Gender Ratio", figsize = (3,3))

df.groupby("Gender").size().plot(kind = "bar",title = "Gender Ratio", figsize = (3,3))

"""# **Gender wise purchase**"""

font1 = {'family':'serif','color':'blue','size':20}
mylabels = ["Female","Male"]
mycolor = ["hotpink","Orange"]
df.groupby('Gender').sum()['Purchase'].plot(kind = 'pie', autopct = "%0.1f", figsize = (6,6), labels = mylabels, colors = mycolor, shadow = True, startangle = 180)
plt.title("Gender wise Purchase", fontdict = font1)
plt.legend(title = "Gender:")

df.groupby('Gender').mean()['Purchase'].plot(kind = 'pie', autopct = "%0.1f", figsize = (3,3))

"""# **Analysing Age wise & Marital Status wise**"""

df.groupby("Age").size().plot(kind = "bar",figsize = (12, 6), title = 'Purchase Distribution by Age')

lst =[]
for i in df["Age"].unique():
  lst.append([i, df[df['Age'] == i]['Product_ID'].nunique()])
data = pd.DataFrame(lst, columns=["Age","Product_ID"])

data

data.plot.bar(x = "Age", figsize = (6,5))

df.groupby("Age").sum()["Purchase"].plot(kind = "bar",x = "Age", y = "Purchase", title = "Amount Spend by Age")

df.groupby("Age").mean()["Purchase"].plot(kind = "pie", autopct = "%.1f%%", title = "Avg Purchased amount Spend by Age wise")

df.groupby("Marital_Status").size().plot(kind = "pie",autopct = "%.1f%%", title = "count of Martial status")

df.groupby("Marital_Status").sum()["Purchase"].plot(kind = "pie",autopct = "%.1f%%", title = "Avg Purchased amount Spend by Martial status wise")

df.groupby("Gender").size().plot(kind = "pie",autopct = "%.1f%%", title = "Gender wise population")

"""#**Multi Coulms Analysis**"""

sns.set(rc = {"figure.figsize" : (10,5)})
sns.countplot(x = "Age",hue = "Gender", data = df)

sns.set(rc = {"figure.figsize" : (10,5)})
sns.countplot( y = "City_Category", hue = "Age", data = df)



sns.set(rc = {"figure.figsize" : (10,5)})
sns.countplot( x = "Age", hue = "Marital_Status", data = df)

sns.set(rc = {"figure.figsize" : (10,5)})
sns.countplot( x = "Marital_Status", hue = "Gender", data = df)

sns.set(rc = {"figure.figsize" : (5,5)})
sns.countplot( x = df["Gender"])

sns.countplot(x = df['City_Category'], palette = "Set2")

sns.countplot(x = df['City_Category'], hue = 'Age', data = df, palette = "Set2")

sns.countplot(x = 'Marital_Status', hue = 'City_Category', data = df)

df.groupby("Age").size().plot(kind = "pie", autopct = "%0.1f%%", figsize = (6,6))

df.groupby("Age").sum()["Purchase"].plot(kind = "pie", autopct = "%0.f%%")

df.groupby("Age").mean()["Purchase"].plot(kind = "pie", autopct = "%0.f%%")

sns.countplot(x = df["Stay_In_Current_City_Years"])

df.groupby("Stay_In_Current_City_Years").size().plot(kind = "pie", autopct = "%.1f%%")

sns.countplot(x = "Stay_In_Current_City_Years", hue ="Gender", data = df)

sns.countplot(x = "Stay_In_Current_City_Years", hue ="Marital_Status", data = df)

sns.countplot(x = 'Stay_In_Current_City_Years', hue = 'City_Category', data = df)

sns.countplot(x = df['Occupation'])

df.groupby('Occupation').size().sort_values().plot(kind = 'bar')

sns.countplot(x = 'Occupation', hue = 'Gender', data = df)

sns.countplot(x = 'Product_Category_1', hue = 'Marital_Status', data = df)

l = []
for i in range(len(df)):
    l.append(df['Gender'][i] +"_"+ str(df['Marital_Status'][i]))

df['MaritalGender'] = l

df.head()

sns.countplot(x = df["MaritalGender"])

sns.countplot(x = "MaritalGender", hue = "Age", data = df)

sns.countplot(x = "Product_Category_1", hue = "MaritalGender", data = df)

sns.countplot(x = "MaritalGender", hue = "Stay_In_Current_City_Years", data = df)

sns.countplot(x = df['City_Category'], hue = df['MaritalGender'])

